apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    name: gateway
spec:
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    nodePort: 32000
  selector:
    name: gateway
  type: NodePort
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: gateway
  labels:
    name: gateway
spec:
  replicas: 1
  selector:
    name: gateway
  template:
    metadata:
      labels:
        name: gateway
    spec:
      containers:
      - name: gateway
        image: kube-sidecar-proxy:0.1
        ports:
        - containerPort: 6379
        env:
        - name: CONTROLLER_URL
          value: http://$(CONTROLLER_SERVICE_HOST):$(CONTROLLER_SERVICE_PORT)
        - name: TENANT_TOKEN
          value: "12345"
        - name: TENANT_ID
          value: local
        - name: VCAP_SERVICES_MESSAGEHUB_0_CREDENTIALS_KAFKA_BROKERS_SASL_0
          value: $(KAFKA_SERVICE_HOST):$(KAFKA_SERVICE_PORT)
        - name: REGISTRY_URL
          value: http://$(REGISTRY_SERVICE_HOST):$(REGISTRY_SERVICE_PORT)
        - name: REGISTRY_TOKEN
          value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0NjY3NzU5NjMsIm5hbWVzcGFjZSI6Imdsb2JhbC5nbG9iYWwifQ.Gbz4G_O0OfJZiTuX6Ce4heU83gSWQLr5yyiA7eZNqdY
        - name: SERVICE
          value: gateway
        - name: CONTROLLER_POLL
          value: 15s
        - name: REGISTER
          value: "false"