apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: logserver
  name: logserver
spec: 
  clusterIP: "10.0.0.220"
  ports: 
    - 
      name: kibana
      nodePort: 30500
      port: 5601
      protocol: TCP
      targetPort: 5601
    - 
      name: es1
      nodePort: 30200
      port: 9200
      protocol: TCP
      targetPort: 9200
    - 
      name: es2
      nodePort: 30300
      port: 9300
      protocol: TCP
      targetPort: 9300
    - 
      name: logstashport
      nodePort: 30092
      port: 8092
      protocol: TCP
      targetPort: 8092
  selector: 
    name: logserver
  type: NodePort
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: logserver
  labels:
    name: logserver
spec:
  replicas: 1
  selector:
    name: logserver
  template:
    metadata:
      labels:
        name: logserver
    spec:
      containers:
      - name: es
        image: elasticsearch
#        command: [ "elasticsearch", "-Des.index.analysis.analyzer.default.type=keyword"]
        ports:
        - containerPort: 9200
        - containerPort: 9300
      - name: logstash
        image: logstash
        command: [ "logstash", "--verbose", "-e", "input { beats {codec=>'json' port=>8092 type=>'nginx'}} output {elasticsearch {hosts =>'localhost:9200' codec=>'json' index=>'nginx'} stdout { codec => rubydebug }} "]
        ports:
        - containerPort: 8092
      - name: kibana
        image: kibana
        ports:
        - containerPort: 5601
        env:
        - name: ELASTICSEARCH_URL
          value: "http://localhost:9200"
