apiVersion: v1
kind: ReplicationController
metadata:
  name: details-v1
  labels:
    name: details-v1
spec:
  replicas: 1
  selector:
    name: details-v1
  template:
    metadata:
      labels:
        name: details-v1
    spec:
      containers:
      - name: details
        image: amalgam8/a8-examples-bookinfo-details:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
      - name: servicereg
        image: amalgam8/a8-sidecar:0.1
        imagePullPolicy: IfNotPresent
        args:
          - --proxy=false
          - --log=false
          - --supervise=false
        env:
        - name: SERVICE
          value: details:v1
        - name: REGISTRY_URL
          value: http://$(REGISTRY_SERVICE_HOST):$(REGISTRY_SERVICE_PORT)
        - name: REGISTRY_TOKEN
          value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0NjY3NzU5NjMsIm5hbWVzcGFjZSI6Imdsb2JhbC5nbG9iYWwifQ.Gbz4G_O0OfJZiTuX6Ce4heU83gSWQLr5yyiA7eZNqdY
        - name: ENDPOINT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ENDPOINT_PORT
          value: "9080"
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: ratings-v1
  labels:
    name: ratings-v1
spec:
  replicas: 1
  selector:
    name: ratings-v1
  template:
    metadata:
      labels:
        name: ratings-v1
    spec:
      containers:
      - name: ratings
        image: amalgam8/a8-examples-bookinfo-ratings:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
      - name: servicereg
        image: amalgam8/a8-sidecar:0.1
        imagePullPolicy: IfNotPresent
        args:
          - --proxy=false
          - --log=false
          - --supervise=false
        env:
        - name: SERVICE
          value: ratings:v1
        - name: REGISTRY_URL
          value: http://$(REGISTRY_SERVICE_HOST):$(REGISTRY_SERVICE_PORT)
        - name: REGISTRY_TOKEN
          value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0NjY3NzU5NjMsIm5hbWVzcGFjZSI6Imdsb2JhbC5nbG9iYWwifQ.Gbz4G_O0OfJZiTuX6Ce4heU83gSWQLr5yyiA7eZNqdY
        - name: ENDPOINT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ENDPOINT_PORT
          value: "9080"
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: reviews-v1
  labels:
    name: reviews-v1
spec:
  replicas: 1
  selector:
    name: reviews-v1
  template:
    metadata:
      labels:
        name: reviews-v1
    spec:
      containers:
      - name: reviews
        image: amalgam8/a8-examples-bookinfo-reviews:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
      - name: serviceproxy
        image: amalgam8/a8-sidecar:0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
        env:
        - name: CONTROLLER_URL
          value: http://$(CONTROLLER_SERVICE_HOST):$(CONTROLLER_SERVICE_PORT)
        - name: TENANT_TOKEN
          value: "12345"
        - name: TENANT_ID
          value: local
        - name: KAFKA_BROKER
          value: $(KAFKA_SERVICE_HOST):$(KAFKA_SERVICE_PORT)
        - name: SERVICE
          value: reviews:v1
        - name: REGISTRY_URL
          value: http://$(REGISTRY_SERVICE_HOST):$(REGISTRY_SERVICE_PORT)
        - name: REGISTRY_TOKEN
          value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0NjY3NzU5NjMsIm5hbWVzcGFjZSI6Imdsb2JhbC5nbG9iYWwifQ.Gbz4G_O0OfJZiTuX6Ce4heU83gSWQLr5yyiA7eZNqdY
        - name: ENDPOINT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ENDPOINT_PORT
          value: "9080"
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: reviews-v2
  labels:
    name: reviews-v2
spec:
  replicas: 1
  selector:
    name: reviews-v2
  template:
    metadata:
      labels:
        name: reviews-v2
    spec:
      containers:
      - name: reviews
        image: amalgam8/a8-examples-bookinfo-reviews:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
      - name: serviceproxy
        image: amalgam8/a8-sidecar:0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
        env:
        - name: CONTROLLER_URL
          value: http://$(CONTROLLER_SERVICE_HOST):$(CONTROLLER_SERVICE_PORT)
        - name: TENANT_TOKEN
          value: "12345"
        - name: TENANT_ID
          value: local
        - name: KAFKA_BROKER
          value: $(KAFKA_SERVICE_HOST):$(KAFKA_SERVICE_PORT)
        - name: SERVICE
          value: reviews:v2
        - name: REGISTRY_URL
          value: http://$(REGISTRY_SERVICE_HOST):$(REGISTRY_SERVICE_PORT)
        - name: REGISTRY_TOKEN
          value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0NjY3NzU5NjMsIm5hbWVzcGFjZSI6Imdsb2JhbC5nbG9iYWwifQ.Gbz4G_O0OfJZiTuX6Ce4heU83gSWQLr5yyiA7eZNqdY
        - name: ENDPOINT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ENDPOINT_PORT
          value: "9080"
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: reviews-v3
  labels:
    name: reviews-v3
spec:
  replicas: 1
  selector:
    name: reviews-v3
  template:
    metadata:
      labels:
        name: reviews-v3
    spec:
      containers:
      - name: reviews
        image: amalgam8/a8-examples-bookinfo-reviews:v3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
      - name: serviceproxy
        image: amalgam8/a8-sidecar:0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
        env:
        - name: CONTROLLER_URL
          value: http://$(CONTROLLER_SERVICE_HOST):$(CONTROLLER_SERVICE_PORT)
        - name: TENANT_TOKEN
          value: "12345"
        - name: TENANT_ID
          value: local
        - name: KAFKA_BROKER
          value: $(KAFKA_SERVICE_HOST):$(KAFKA_SERVICE_PORT)
        - name: SERVICE
          value: reviews:v3
        - name: REGISTRY_URL
          value: http://$(REGISTRY_SERVICE_HOST):$(REGISTRY_SERVICE_PORT)
        - name: REGISTRY_TOKEN
          value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0NjY3NzU5NjMsIm5hbWVzcGFjZSI6Imdsb2JhbC5nbG9iYWwifQ.Gbz4G_O0OfJZiTuX6Ce4heU83gSWQLr5yyiA7eZNqdY
        - name: ENDPOINT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ENDPOINT_PORT
          value: "9080"
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: productpage-v1
  labels:
    name: productpage-v1
spec:
  replicas: 1
  selector:
    name: productpage-v1
  template:
    metadata:
      labels:
        name: productpage-v1
    spec:
      containers:
      - name: productpage
        image: amalgam8/a8-examples-bookinfo-productpage:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
      - name: serviceproxy
        image: amalgam8/a8-sidecar:0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
        env:
        - name: CONTROLLER_URL
          value: http://$(CONTROLLER_SERVICE_HOST):$(CONTROLLER_SERVICE_PORT)
        - name: TENANT_TOKEN
          value: "12345"
        - name: TENANT_ID
          value: local
        - name: KAFKA_BROKER
          value: $(KAFKA_SERVICE_HOST):$(KAFKA_SERVICE_PORT)
        - name: SERVICE
          value: productpage:v1
        - name: REGISTRY_URL
          value: http://$(REGISTRY_SERVICE_HOST):$(REGISTRY_SERVICE_PORT)
        - name: REGISTRY_TOKEN
          value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0NjY3NzU5NjMsIm5hbWVzcGFjZSI6Imdsb2JhbC5nbG9iYWwifQ.Gbz4G_O0OfJZiTuX6Ce4heU83gSWQLr5yyiA7eZNqdY
        - name: ENDPOINT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ENDPOINT_PORT
          value: "9080"
