# Copyright 2016 IBM Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

#########Holiday Check's Mesos-in-the-Box
zookeeper:
  image: mesoscloud/zookeeper:3.4.6-ubuntu-14.04
  net: host
  environment:
     - MYID=1
     - SERVERS=localhost

master:
  image: mesosphere/mesos-master:0.26.0-0.2.145.ubuntu1404
  net: host
  environment:
    - MESOS_HOSTNAME=192.168.33.33
    - MESOS_IP=192.168.33.33
    - MESOS_QUORUM=1
    - MESOS_ZK=zk://localhost:2181/mesos

slave:
  image: mesosphere/mesos-slave-dind:0.2.4_mesos-0.26.0_docker-1.8.2_ubuntu-14.04.3
  net: host
  privileged: true
  environment:
    - MESOS_HOSTNAME=192.168.33.33
    - MESOS_IP=192.168.33.33
    - MESOS_PORT=5051
    - MESOS_MASTER=zk://localhost:2181/mesos
    - MESOS_CONTAINERIZERS=docker,mesos
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /var/run/docker.sock:/var/run/docker.sock

marathon:
  image: mesosphere/marathon:v0.15.2
  net: host
  environment:
    - MARATHON_HOSTNAME=192.168.33.33
    - MARATHON_HTTPS_ADDRESS=192.168.33.33
    - MARATHON_HTTP_ADDRESS=192.168.33.33
    - MARATHON_MASTER=zk://localhost:2181/mesos
    - MARATHON_ZK=zk://localhost:2181/marathon

chronos:
  image: mesoscloud/chronos:2.4.0-ubuntu-14.04
  net: host
  environment:
   - CHRONOS_HTTP_PORT=4400
   - CHRONOS_MASTER=zk://localhost:2181/mesos
   - CHRONOS_ZK_HOSTS=localhost:2181

#########Amalgam8 Control Plane components
###############Integration Bus############
kafka:
  image: rshriram/kafka-nozk-0.9
  net: host
  environment:
    - ADVERTISED_HOST=192.168.33.33
    - ADVERTISED_PORT=9092
    - AUTO_CREATE_TOPICS=true
    - ZOOKEEPER_HOST=localhost:2181
  ports:
    - "9092:9092"

##########ELK Stack##############
es:
  image: elasticsearch
  ports:
    - 9300
    - "30200:9200"
logstash:
  image: logstash
  command: logstash --verbose -e "input { beats {codec=>'json' port=>8092 type=>'nginx'}} output {elasticsearch {hosts =>'es:9200' codec=>'json' index=>'nginx'} stdout { codec => rubydebug }}"
  ports:
    - "8092:8092"
  links:
    - es
kibana:
  image: kibana
  links:
    - es
  environment:
    - ELASTICSEARCH_URL=http://es:9200
  ports:
    - "30500:5601"
